spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mobile2
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ite@123!456
  expiration: 86400000
openweathermap:
  apiKey: f4d52585bb461a5d425ef2763e226343